#!/usr/bin/env python3
"""Every stub of the local test fleet, on every node, through both doors.

    python3 deploy/compose/local-test.matrix.py

Run it after `local-test.seed.py`. Where the seed's `--check` asks "did the seed
land on all three nodes", this asks the harder question: does each individual
stub answer the same way whichever door the request came in by, and on whichever
node happened to serve it. Two transports times three nodes is six runs of each
case, and the interesting failures are the ones that show up in only one column.

**Both doors, because they are different code paths to the same stub and they do
not always agree.** The router dispatches to an imposter in-process, which is how
a route reaches the https imposter over plain http, and why a TCP-reset fault
arrives here as a `502` carrying `x-rift-fault` instead of killing the
connection. A sweep that used one door would have called the fleet healthy while
the other was dark — which it was, for `payments`, until a route existed for it.

Stateful stubs are the reason this is a separate tool rather than more probes in
the seed's `--check`. They cannot be asserted with one request each:

- **`cat-cycle`** cycles its responses per stub per engine, and both transports
  on one node share that engine. So the assertion is that consecutive calls
  through the same door *alternate*, never that the first one is a `202`.
- **scenarios and flow state** are keyed by a header. Each (case, transport,
  node) gets its own flow id, so six runs do not walk one state machine six
  steps and read the answers as disagreement.

Safe to re-run: every stateful case takes a flow id unique to the run, so the
sweep never inherits state from a previous one. The `space`-scoped stubs are the
exception and must keep their fixed ids (`team-a`, `team-b`) — the flow id *is*
what selects the stub — but they only read.

Exit status is 0 only if every check passed.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import time
import uuid

NODES = (1, 2, 3)

CATALOG, ORDERS, PAYMENTS, EDGE, LEDGER = 4545, 4546, 4547, 4548, 4549

# How the router addresses each imposter: the route's path prefix, and the Host a
# host-matched route needs. Mirrors `ROUTE_TABLE` in `local-test.seed.py` — if a
# route is renamed there, this is the other end that has to move with it.
ROUTER = {
    CATALOG: {"prefix": "/catalog", "host": None},
    ORDERS: {"prefix": "/orders-api", "host": None},
    PAYMENTS: {"prefix": "/pay", "host": None},
    EDGE: {"prefix": "", "host": "edge.test"},
    LEDGER: {"prefix": "/ledger", "host": None},
}

# A fresh flow id per RUN, not just per (transport, node).
#
# Without this the sweep passes once and fails ever after against the same fleet:
# the scenario walk expects `Started -> paid -> fulfilled` and the second run finds
# the timeline already at `fulfilled`, so it reads `[200, 200, 200, 200]` and calls
# a working stub broken. Re-seeding between runs hid it, because recreating an
# imposter drops its flow state — which is exactly the kind of accident that makes
# a check look idempotent when it is not.
RUN = uuid.uuid4().hex[:8]

results: list[tuple[str, str, int, bool, str]] = []


def curl(url, method="GET", headers=None, body=None, insecure=False, timeout=15):
    """One request, via `curl` rather than `urllib`.

    Deliberate: a TCP-reset fault has no HTTP response at all, and `curl` reports
    that as an exit code while `urllib` raises an exception whose class varies by
    Python version. Here the transport-level failure IS one of the assertions.
    """
    with tempfile.NamedTemporaryFile(suffix=".body") as out:
        cmd = ["curl", "-s", "-m", str(timeout), "-o", out.name, "-w", "%{http_code}"]
        if insecure:
            # The https imposter's certificate is generated by the engine and
            # signed by nobody.
            cmd.append("-k")
        if method != "GET":
            cmd += ["-X", method]
        for name, value in (headers or {}).items():
            cmd += ["-H", f"{name}: {value}"]
        if body is not None:
            cmd += ["--data", body]
        cmd.append(url)

        started = time.time()
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
        elapsed = time.time() - started
        payload = open(out.name, encoding="utf-8", errors="replace").read()

    try:
        status = int(proc.stdout.strip() or 0)
    except ValueError:
        status = 0
    return {"status": status, "body": payload, "elapsed": elapsed, "exit": proc.returncode}


def url_for(transport, node, port, path, https=False):
    if transport == "direct":
        # The published imposter port follows the rift-N convention: 4545 -> 14545.
        return f"{'https' if https else 'http'}://localhost:{node}{port % 10000}{path}"
    # Always plain http on the front door, even for the https imposter.
    return f"http://localhost:{node}2527{ROUTER[port]['prefix']}{path}"


def headers_for(transport, port, extra):
    merged = dict(extra or {})
    if transport == "router":
        host = ROUTER[port]["host"]
        if host:
            merged["Host"] = host
    return merged


def expect(status=None, contains=None, min_elapsed=None):
    def check(r):
        if status is not None and r["status"] != status:
            return False, f"status {r['status']} != {status}: {r['body'][:80]}"
        if contains is not None and contains not in r["body"]:
            return False, f"body lacks {contains!r}: {r['body'][:80]}"
        # A stub that declares a delay must actually take it — a `wait` silently
        # dropped still answers 200 with the right body.
        if min_elapsed is not None and r["elapsed"] < min_elapsed:
            return False, f"returned in {r['elapsed']:.3f}s, wanted >= {min_elapsed}s"
        return True, f"{r['status']} {r['elapsed']:.3f}s"

    return check


CASES = [
    # ── catalog-api: the predicate and response gallery ───────────────────
    dict(name="cat-search (deepEquals)", port=CATALOG, path="/products?q=widget",
         check=expect(200, '"matched":"deepEquals"')),
    dict(name="cat-list (equals)", port=CATALOG, path="/products",
         check=expect(200, '"matched":"equals"')),
    dict(name="cat-sku-regex (matches)", port=CATALOG, path="/products/SKU-1001",
         check=expect(200, "matches (regex)")),
    dict(name="cat-templated", port=CATALOG, path="/products/SKU-1001/detail",
         check=expect(200, '"sku":"SKU-1001"')),
    dict(name="cat-contains", port=CATALOG, path="/anything", method="POST",
         body="a needle here", check=expect(200, '"matched":"contains"')),
    dict(name="cat-endswith", port=CATALOG, path="/feed.json",
         check=expect(200, '"matched":"endsWith"')),
    dict(name="cat-admin-unauth (not+exists)", port=CATALOG, path="/admin",
         check=expect(401, "no credentials")),
    dict(name="cat-admin (exists)", port=CATALOG, path="/admin",
         headers={"Authorization": "Bearer x"}, check=expect(200, '"matched":"exists"')),
    dict(name="cat-or /a", port=CATALOG, path="/a", check=expect(200, '"matched":"or"')),
    dict(name="cat-or /b", port=CATALOG, path="/b", check=expect(200, '"matched":"or"')),
    dict(name="cat-slow (_behaviors.wait)", port=CATALOG, path="/slow",
         check=expect(200, "_behaviors.wait", min_elapsed=0.2)),
    dict(name="cat-flaky (latency fault)", port=CATALOG, path="/flaky",
         check=expect(200, "latency fault", min_elapsed=0.7)),
    dict(name="cat-defaultResponse", port=CATALOG, path="/no-such-thing",
         check=expect(404, "no stub matched")),

    # ── orders-api ────────────────────────────────────────────────────────
    dict(name="ord-health", port=ORDERS, path="/health", check=expect(200, '"ok":true')),

    # ── payments-api: https, and a fault that is not a status ─────────────
    dict(name="pay-charge (https)", port=PAYMENTS, path="/charge", method="POST",
         https=True, check=expect(201, '"status":"captured"')),
    dict(name="pay-outage (error fault)", port=PAYMENTS, path="/outage", https=True,
         check=expect(503, "upstream unavailable")),

    # ── edge-proxy ────────────────────────────────────────────────────────
    dict(name="edge-health", port=EDGE, path="/health", check=expect(200, '"ok":true')),
    dict(name="edge-proxyonce (replay)", port=EDGE, path="/products",
         check=expect(200, "Anvil")),

    # ── ledger-api ────────────────────────────────────────────────────────
    dict(name="led-health (global stub)", port=LEDGER, path="/health",
         check=expect(200, '"ok":true')),
    dict(name="led-space team-a", port=LEDGER, path="/balance",
         headers={"X-Flow-Id": "team-a"}, check=expect(200, '"owner":"team-a"')),
    dict(name="led-space team-b", port=LEDGER, path="/balance",
         headers={"X-Flow-Id": "team-b"}, check=expect(200, '"owner":"team-b"')),
]


def run_case(case, transport, node):
    port = case["port"]
    extra = dict(case.get("headers") or {})
    https = bool(case.get("https")) and transport == "direct"
    r = curl(
        url_for(transport, node, port, case["path"], https),
        case.get("method", "GET"),
        headers_for(transport, port, extra),
        case.get("body"),
        insecure=https,
    )
    ok, detail = case["check"](r)
    results.append((case["name"], transport, node, ok, detail))


def run_sequences():
    """The cases one request cannot express."""
    for transport in ("direct", "router"):
        for node in NODES:
            # Responses cycle per stub per engine, and both doors on one node
            # share it — so alternation is the claim, not the absolute value.
            url = url_for(transport, node, CATALOG, "/cycle")
            got = [curl(url, headers=headers_for(transport, CATALOG, {}))["status"]
                   for _ in range(4)]
            ok = len(set(got)) == 2 and got[0] != got[1] and got[0] == got[2]
            results.append(("cat-cycle alternates", transport, node, ok, str(got)))

            # Started -> paid -> fulfilled, then it holds: the third stub gates on
            # the state without advancing it.
            url = url_for(transport, node, ORDERS, "/orders")
            head = headers_for(transport, ORDERS, {"X-Mock-Space": f"walk-{transport}-{node}-{RUN}"})
            got = [curl(url, "POST", head)["status"] for _ in range(4)]
            results.append(("ord-scenario walk", transport, node,
                            got == [402, 201, 200, 200], str(got)))

            # The Rhai script: two 503s then 200, scoped to this flow id.
            url = url_for(transport, node, LEDGER, "/warmup")
            head = headers_for(transport, LEDGER, {"X-Flow-Id": f"warm-{transport}-{node}-{RUN}"})
            got = [curl(url, headers=head)["status"] for _ in range(4)]
            results.append(("led-retry walk (rhai)", transport, node,
                            got == [503, 503, 200, 200], str(got)))

            # `stateOps` runs after the body is rendered, so the count in the body
            # is the one BEFORE this request: "", then 1, then 2.
            head = headers_for(transport, LEDGER, {"X-Flow-Id": f"count-{transport}-{node}-{RUN}"})
            seen = []
            for i in range(3):
                url = url_for(transport, node, LEDGER, f"/counter?id=r{i}")
                body = curl(url, headers=head)["body"]
                try:
                    seen.append(json.loads(body)["hitsBefore"])
                except (ValueError, KeyError):
                    seen.append(f"?{body[:20]}")
            results.append(("led-counter walk (stateOps)", transport, node,
                            seen == ["", "1", "2"], str(seen)))

            # A TCP reset has no status. Direct, the connection dies and curl
            # exits non-zero; through the router it is a 502 with `x-rift-fault`,
            # because the front terminates its own connection and cannot forward
            # a raw reset. What must never happen is a clean 2xx.
            https = transport == "direct"
            r = curl(url_for(transport, node, PAYMENTS, "/reset", https),
                     headers=headers_for(transport, PAYMENTS, {}), insecure=https)
            ok = r["status"] == 0 or r["status"] >= 500
            results.append(("pay-reset is never a clean answer", transport, node, ok,
                            f"exit={r['exit']} status={r['status']}"))


def main() -> int:
    argparse.ArgumentParser(description=__doc__.splitlines()[0]).parse_args()

    for case in CASES:
        for transport in ("direct", "router"):
            for node in NODES:
                run_case(case, transport, node)
    run_sequences()

    by_case: dict[str, list] = {}
    for name, transport, node, ok, detail in results:
        by_case.setdefault(name, []).append((transport, ok))
    for name, rows in by_case.items():
        direct = sum(1 for t, ok in rows if t == "direct" and ok)
        router = sum(1 for t, ok in rows if t == "router" and ok)
        mark = "ok  " if direct == len(NODES) and router == len(NODES) else "FAIL"
        print(f"  {mark} {name:34} direct {direct}/{len(NODES)}  router {router}/{len(NODES)}")

    bad = [r for r in results if not r[3]]
    print(f"\n{len(results) - len(bad)}/{len(results)} checks passed")
    if bad:
        print("\nfailures:")
        for name, transport, node, _, detail in bad:
            print(f"  - {name} [{transport} node{node}]: {detail}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
